packages = [
    { name = "git", config = ".gitconfig" },
    { name = "less" },
    { name = "helix", config = ".config/helix/*" },
    { name = "fish", config = ".config/fish/*", setup = "chsh -s /usr/bin/fish" },
    { name = "eza" },
    { name = "starship" },
    { name = "fisher" },
    { name = "tmux" },
    { name = "tree" },

    { name = "steam" },
    { name = "telegram-desktop" },
]
